# Generated by Django 4.2.23 on 2025-11-15 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('number_repetitions', models.IntegerField(default=0, verbose_name='Количество сделанных повторов')),
                ('status', models.CharField(choices=[('1', 'Неизвестно'), ('2', 'Изучаю'), ('3', 'Повторяю'), ('4', 'Изучил')], default='1', max_length=1, verbose_name='Этап запоминания')),
                ('core_words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wordscard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Накопитель слов',
                'verbose_name_plural': 'Накопитель слов',
            },
        ),
    ]
