# Generated by Django 4.2.23 on 2025-08-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordsuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "Неизвестно"),
                    ("2", "Изучаю"),
                    ("3", "Повторяю"),
                    ("4", "Изучил"),
                ],
                default="1",
                max_length=1,
                verbose_name="Этап запоминания",
            ),
        ),
    ]
