# Generated by Django 6.0 on 2025-12-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.JSONField(blank=True, verbose_name='Английский')),
                ('word_ru', models.JSONField(blank=True, verbose_name='Русский')),
                ('transcription', models.JSONField(blank=True, verbose_name='Транскрипция')),
                ('phrases_en', models.JSONField(blank=True, verbose_name='Фразы-Английский')),
                ('phrases_ru', models.JSONField(blank=True, verbose_name='Фразы-Русский')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
    ]
