# Generated by Django 5.2.3 on 2025-06-19 11:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер повтора')),
            ],
            options={
                'verbose_name': 'Номер повтора',
                'verbose_name_plural': 'Номера повтора',
            },
        ),
        migrations.CreateModel(
            name='WordsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.JSONField(blank=True, verbose_name='Английский')),
                ('word_ru', models.JSONField(blank=True, verbose_name='Русский')),
                ('transcription', models.JSONField(blank=True, verbose_name='Транскрипция')),
                ('phrases_en', models.JSONField(blank=True, verbose_name='Фразы-Английский')),
                ('phrases_ru', models.JSONField(blank=True, verbose_name='Фразы-Русский')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='IntroductionWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.CharField(max_length=100, verbose_name='На английском')),
                ('transcription', models.CharField(max_length=100, verbose_name='Транскрипция')),
                ('word_ru', models.CharField(max_length=100, verbose_name='На русском')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Слова для ознакомления',
                'verbose_name_plural': 'Слова для ознакомления',
            },
        ),
        migrations.CreateModel(
            name='SettingsWordNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_words', models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(5)], verbose_name='Количество слов за день')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Количество слов за день',
                'verbose_name_plural': 'Количество за день',
            },
        ),
        migrations.CreateModel(
            name='Word_Accumulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.CharField(max_length=100, verbose_name='Слово на английском')),
                ('word_ru', models.CharField(max_length=100, verbose_name='Слово на русском')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Накопитель слов',
                'verbose_name_plural': 'Накопитель слов',
            },
        ),
        migrations.CreateModel(
            name='WordsConfigJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WORD_DATA', models.JSONField(null=True)),
                ('WORD_USER', models.JSONField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configs',
            },
        ),
        migrations.CreateModel(
            name='WordsToRepeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Слово')),
                ('repeat_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.repeatnumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Слово для повторения',
                'verbose_name_plural': 'Слова для повторения',
            },
        ),
    ]
