# Generated by Django 4.2.23 on 2025-06-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='introductionwords',
            name='created',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='Дата создания'),
        ),
    ]
