# Generated by Django 3.1.4 on 2023-07-09 12:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.CharField(max_length=100, verbose_name='На английском')),
                ('transcription', models.CharField(max_length=100, verbose_name='Транскрипция')),
                ('word_ru', models.CharField(max_length=100, verbose_name='На русском')),
            ],
            options={
                'verbose_name': 'Слова для ознакомления',
                'verbose_name_plural': 'Слова для ознакомления',
            },
        ),
        migrations.CreateModel(
            name='SettingsWordNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_words', models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(5)], verbose_name='Количество слов за день')),
            ],
            options={
                'verbose_name': 'Количество слов за день',
                'verbose_name_plural': 'Количество за день',
            },
        ),
        migrations.CreateModel(
            name='Word_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Статус слова')),
            ],
            options={
                'verbose_name': 'Статус слова',
                'verbose_name_plural': 'Статус слов',
            },
        ),
        migrations.CreateModel(
            name='WordsCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.CharField(blank=True, max_length=100, verbose_name='На аглийском')),
                ('transcription', models.CharField(blank=True, max_length=100, verbose_name='Транскрипция')),
                ('word_ru', models.CharField(blank=True, max_length=100, verbose_name='На русском')),
                ('phrases_en', models.TextField(blank=True, verbose_name='Фразы на английском')),
                ('phrases_ru', models.TextField(blank=True, verbose_name='Фразы на русском')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='WordsConfigJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WORD_DATA', models.JSONField(null=True)),
                ('WORD_USER', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Configs',
            },
        ),
        migrations.CreateModel(
            name='WordsToRepead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Слово для повторения',
                'verbose_name_plural': 'Слова для повторения',
            },
        ),
        migrations.CreateModel(
            name='Word_Accumulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Слово')),
                ('word_status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='words.word_status', verbose_name='Статус слова')),
            ],
            options={
                'verbose_name': 'Накопитель слов',
                'verbose_name_plural': 'Накопитель слов',
            },
        ),
    ]
