# Generated by Django 3.1.4 on 2023-05-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordsCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.TextField(blank=True)),
                ('transcription', models.TextField(blank=True)),
                ('word_ru', models.TextField(blank=True)),
                ('phraze_en', models.TextField(blank=True)),
                ('phraze_ru', models.TextField(blank=True)),
                ('number_repetitions', models.TextField(blank=True)),
            ],
        ),
    ]
