# Generated by Django 4.2.23 on 2025-11-15 15:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_words', models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(5)], verbose_name='Количество слов за день')),
                ('number_repetitions', models.CharField(choices=[('1', 'Слабый уровень:  3 повторения'), ('2', 'Нормально уровень: 5 повторений'), ('3', 'Хорошо уровень: 6 повторений'), ('4', 'Отлично: 8 повторений'), ('5', 'Максимальный результат: 10 повторений')], default=3, max_length=1, verbose_name='Как хорошо вы хотите запомнить слово')),
                ('translation_list', models.BooleanField(choices=[(True, 'Показывать перевод в списке слов'), (False, 'Спрятать перевод в списке слов')], default=True, verbose_name='Спрятать/Показать перевод в списке слов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
