# Generated by Django 4.2.23 on 2025-06-26 13:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WordsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_words",
                    models.IntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(5),
                        ],
                        verbose_name="Количество слов за день",
                    ),
                ),
                (
                    "number_repetitions",
                    models.CharField(
                        choices=[
                            ("2", "Слабо"),
                            ("3", "Нормально"),
                            ("4", "Хорошо"),
                            ("5", "Отлично"),
                            ("6", "Максимальный результат"),
                        ],
                        default=3,
                        max_length=1,
                        verbose_name="Количество повторов при изучении",
                    ),
                ),
                (
                    "translation_list",
                    models.BooleanField(
                        choices=[
                            (True, "Показывать перевод в списке слов"),
                            (False, "Спрятать перевод в списке слов"),
                        ],
                        default=True,
                        verbose_name="Спрятать перевод в списке слов",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Количество слов за день",
                "verbose_name_plural": "Количество за день",
            },
        ),
    ]
