# Generated by Django 4.2.23 on 2025-08-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordssettings",
            name="number_repetitions",
            field=models.CharField(
                choices=[
                    ("1", "Слабо 3 раза"),
                    ("2", "Нормально 5 раз"),
                    ("3", "Хорошо 6 раз"),
                    ("4", "Отлично 8 раз"),
                    ("5", "Максимальный результат 10 раз"),
                ],
                default=3,
                max_length=1,
                verbose_name="Как хорошо вы хотите запомнить слово",
            ),
        ),
        migrations.AlterField(
            model_name="wordssettings",
            name="translation_list",
            field=models.BooleanField(
                choices=[
                    (True, "Показывать перевод в списке слов"),
                    (False, "Спрятать перевод в списке слов"),
                ],
                default=True,
                verbose_name="Спрятать/Показать перевод в списке слов",
            ),
        ),
    ]
