# Generated by Django 4.2.23 on 2025-11-26 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordssettings",
            name="max_number_read",
            field=models.IntegerField(
                default=5, validators=[django.core.validators.MaxValueValidator(30)]
            ),
        ),
        migrations.AddField(
            model_name="wordssettings",
            name="number_wirite",
            field=models.IntegerField(default=5),
        ),
    ]
