# Generated by Django 4.2.23 on 2025-11-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_wordssettings_max_number_read_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wordssettings",
            old_name="number_wirite",
            new_name="number_write",
        ),
    ]
