# Generated by Django 4.2.23 on 2025-06-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginLogout',
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
