# Generated by Django 4.2.23 on 2025-06-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('header', '0002_delete_loginlogout_delete_logo_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.BooleanField(default=True, verbose_name='Тема')),
            ],
        ),
    ]
